import { Router } from "express";
import axios from "axios";
import { ai } from "@workspace/integrations-gemini-ai";
import { generateSignal } from "../lib/signal-engine.js";
import { calculateIndicators } from "../lib/indicators.js";
import { detectPatterns } from "../lib/patterns.js";
import { NIFTY50 } from "../lib/constants.js";
import * as angelone from "../lib/angelone.js";
import type { Candle } from "../lib/broker-adapter.js";

// ─── Shared candle fetcher (same as signals.ts) ──────────────────────────────
async function fetchCandles(token: string, interval = "FIFTEEN_MINUTE", exchange = "NSE"): Promise<Candle[]> {
  const now = new Date();
  const from = new Date(now.getTime() - 90 * 24 * 60 * 60 * 1000);
  const pad = (n: number) => n.toString().padStart(2, "0");
  const fmt = (d: Date) =>
    `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())} ${pad(d.getHours())}:${pad(d.getMinutes())}`;

  const raw = await angelone.getCandleData({ exchange, symboltoken: token, interval, fromdate: fmt(from), todate: fmt(now) });
  return raw.map(([ts, open, high, low, close, volume]) => ({
    time: new Date(ts).getTime() / 1000,
    open, high, low, close, volume,
  }));
}

const router = Router();

// ─── Helpers ────────────────────────────────────────────────────────────────

function parseAIResponse(text: string): Record<string, unknown> {
  const jsonMatch = text.match(/\{[\s\S]*\}/);
  if (!jsonMatch) throw new Error("No JSON found in AI response");
  return JSON.parse(jsonMatch[0]);
}

function buildAnalysisPrompt(body: {
  stockName: string;
  timeframe: string;
  candles: Candle[];
  indicators: Record<string, unknown>;
  patterns: { candlestick: string[]; chart: string[] };
  levels?: Record<string, unknown>;
}): string {
  const { stockName, timeframe, candles, indicators, patterns, levels } = body;
  const lastCandle = candles[candles.length - 1];
  return `You are an expert technical analyst for Indian stock markets. Analyze the following stock data and provide a detailed trading signal.

Stock: ${stockName}
Timeframe: ${timeframe}
Current Price: ${lastCandle?.close ?? "N/A"}
Candles analyzed: ${candles.length}

Technical Indicators:
${JSON.stringify(indicators, null, 2)}

Detected Patterns:
- Candlestick: ${patterns.candlestick.join(", ") || "None"}
- Chart: ${patterns.chart.join(", ") || "None"}

Key Levels:
${levels ? JSON.stringify(levels, null, 2) : "N/A"}

Provide your analysis in this exact JSON format:
{
  "signal": "STRONG_BUY|BUY|WEAK_BUY|NEUTRAL|WEAK_SELL|SELL|STRONG_SELL",
  "confidence": 0-100,
  "entry": <price>,
  "target1": <price>,
  "target2": <price>,
  "target3": <price>,
  "stopLoss": <price>,
  "riskReward": <ratio>,
  "reasoning": ["reason1", "reason2", ...],
  "riskFactors": ["risk1", "risk2", ...],
  "summary": "<one paragraph summary>"
}`;
}

function buildCrossVerifyPrompt(params: {
  symbol: string;
  interval: string;
  price: number;
  algoSignal: string;
  algoScore: number;
  algoConfidence: number;
  algoReasons: string[];
  indicators: Record<string, unknown>;
  candlestickPatterns: string[];
  chartPatterns: string[];
  recentPrices: number[];
}): string {
  const {
    symbol, interval, price, algoSignal, algoScore, algoConfidence,
    algoReasons, indicators, candlestickPatterns, chartPatterns, recentPrices,
  } = params;

  const priceChange = recentPrices.length >= 2
    ? (((recentPrices[recentPrices.length - 1] - recentPrices[0]) / recentPrices[0]) * 100).toFixed(2)
    : 'N/A';

  return `You are a world-class technical analysis AI for Indian stock markets (NSE/BSE). You have received a trading signal generated by an algorithmic engine that runs 20+ technical indicators simultaneously. Your job is to INDEPENDENTLY analyze the same data and either CONFIRM or DISPUTE the algorithmic prediction.

═══════════════════════════════════
STOCK INFORMATION
═══════════════════════════════════
Symbol: ${symbol} (NSE/BSE)
Current Price: ₹${price.toFixed(2)}
Timeframe: ${interval}
Price change (${recentPrices.length} candles): ${priceChange}%

═══════════════════════════════════
ALGORITHM ENGINE OUTPUT (20 indicators)
═══════════════════════════════════
Signal: ${algoSignal}
Score: ${algoScore}/20
Confidence: ${algoConfidence}%
Top Reasons:
${algoReasons.slice(0, 8).map((r, i) => `  ${i + 1}. ${r}`).join('\n')}

═══════════════════════════════════
TECHNICAL INDICATORS (live data)
═══════════════════════════════════
RSI (14): ${(indicators as any).rsi?.value?.toFixed(1) ?? 'N/A'} (${(indicators as any).rsi?.divergence ?? 'none'} divergence)
MACD Line: ${(indicators as any).macd?.macdLine?.toFixed(3) ?? 'N/A'}
MACD Signal: ${(indicators as any).macd?.signalLine?.toFixed(3) ?? 'N/A'}
MACD Histogram: ${(indicators as any).macd?.histogram?.toFixed(3) ?? 'N/A'}
EMA9: ${(indicators as any).ema9?.toFixed(2) ?? 'N/A'} | EMA21: ${(indicators as any).ema21?.toFixed(2) ?? 'N/A'}
EMA50: ${(indicators as any).ema50?.toFixed(2) ?? 'N/A'} | EMA200: ${(indicators as any).ema200?.toFixed(2) ?? 'N/A'}
Supertrend: ${(indicators as any).supertrend?.signal ?? 'N/A'} @ ₹${(indicators as any).supertrend?.value?.toFixed(2) ?? 'N/A'}
Bollinger Upper: ${(indicators as any).bollingerBands?.upper?.toFixed(2) ?? 'N/A'} | Middle: ${(indicators as any).bollingerBands?.middle?.toFixed(2) ?? 'N/A'} | Lower: ${(indicators as any).bollingerBands?.lower?.toFixed(2) ?? 'N/A'}
ADX: ${(indicators as any).adx?.adx?.toFixed(1) ?? 'N/A'} (+DI: ${(indicators as any).adx?.plusDI?.toFixed(1) ?? 'N/A'} -DI: ${(indicators as any).adx?.minusDI?.toFixed(1) ?? 'N/A'})
Stochastic %K: ${(indicators as any).stochastic?.k?.toFixed(1) ?? 'N/A'} %D: ${(indicators as any).stochastic?.d?.toFixed(1) ?? 'N/A'}
Volume Ratio: ${(indicators as any).volumeRatio?.toFixed(2) ?? 'N/A'}x average
VWAP: ${(indicators as any).vwap?.toFixed(2) ?? 'N/A'}

═══════════════════════════════════
DETECTED PATTERNS
═══════════════════════════════════
Candlestick: ${candlestickPatterns.join(', ') || 'None detected'}
Chart Patterns: ${chartPatterns.join(', ') || 'None detected'}

═══════════════════════════════════
YOUR TASK
═══════════════════════════════════
1. Independently assess whether the algorithmic signal is CORRECT or INCORRECT
2. Provide your own signal based purely on the data above
3. Calculate an agreement score with the algorithm (0-100%)
4. Highlight any CONFLICTING indicators
5. Give your final CONSENSUS recommendation

Respond in this EXACT JSON format (no markdown, no explanation outside JSON):
{
  "aiSignal": "STRONG_BUY|BUY|WEAK_BUY|NEUTRAL|WEAK_SELL|SELL|STRONG_SELL",
  "aiConfidence": 0-100,
  "aiEntry": <price>,
  "aiTarget1": <price>,
  "aiTarget2": <price>,
  "aiTarget3": <price>,
  "aiStopLoss": <price>,
  "aiRiskReward": <number>,
  "agreementScore": 0-100,
  "verdict": "CONFIRMED|DISPUTED|PARTIAL",
  "consensusSignal": "STRONG_BUY|BUY|WEAK_BUY|NEUTRAL|WEAK_SELL|SELL|STRONG_SELL",
  "consensusConfidence": 0-100,
  "aiReasoning": ["reason1", "reason2", "reason3", "reason4", "reason5"],
  "conflicts": ["conflict1", "conflict2"],
  "riskFactors": ["risk1", "risk2"],
  "chartReading": "<2-3 sentences describing what the chart is showing - trend, momentum, key levels>",
  "tradeRecommendation": "<specific actionable recommendation in 1-2 sentences>"
}`;
}

// ─── Standard AI analysis (user provides candles + their own API key) ─────────

async function callGemini(apiKey: string, model: string, prompt: string): Promise<string> {
  const url = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${apiKey}`;
  const res = await axios.post(url, {
    contents: [{ parts: [{ text: prompt }] }],
    generationConfig: { temperature: 0.3, maxOutputTokens: 4096 },
  });
  return res.data.candidates[0].content.parts[0].text;
}

async function callOpenAI(apiKey: string, model: string, prompt: string): Promise<string> {
  const res = await axios.post(
    "https://api.openai.com/v1/chat/completions",
    {
      model,
      messages: [
        { role: "system", content: "You are an expert stock market technical analyst." },
        { role: "user", content: prompt },
      ],
      temperature: 0.3,
      max_tokens: 4096,
    },
    { headers: { Authorization: `Bearer ${apiKey}`, "Content-Type": "application/json" } }
  );
  return res.data.choices[0].message.content;
}

async function callClaude(apiKey: string, model: string, prompt: string): Promise<string> {
  const res = await axios.post(
    "https://api.anthropic.com/v1/messages",
    {
      model,
      max_tokens: 4096,
      messages: [{ role: "user", content: prompt }],
    },
    {
      headers: {
        "x-api-key": apiKey,
        "anthropic-version": "2023-06-01",
        "Content-Type": "application/json",
      },
    }
  );
  return res.data.content[0].text;
}

// ─── Route: manual analyze (user-supplied candles + API key) ─────────────────

router.post("/analyze", async (req, res) => {
  try {
    const { provider, model, apiKey, stockName, timeframe, candles, indicators, patterns, levels } = req.body as {
      provider: "gemini" | "openai" | "claude";
      model: string;
      apiKey: string;
      stockName: string;
      timeframe: string;
      candles: Candle[];
      indicators: Record<string, unknown>;
      patterns: { candlestick: string[]; chart: string[] };
      levels?: Record<string, unknown>;
    };

    if (!provider || !apiKey || !candles) {
      res.status(400).json({ error: "provider, apiKey, and candles are required" });
      return;
    }

    const prompt = buildAnalysisPrompt({ stockName, timeframe, candles, indicators, patterns, levels });

    let rawText: string;
    switch (provider) {
      case "gemini": rawText = await callGemini(apiKey, model || "gemini-1.5-pro", prompt); break;
      case "openai": rawText = await callOpenAI(apiKey, model || "gpt-4o", prompt); break;
      case "claude": rawText = await callClaude(apiKey, model || "claude-3-5-sonnet-20241022", prompt); break;
      default:
        res.status(400).json({ error: "provider must be gemini, openai, or claude" });
        return;
    }

    const result = parseAIResponse(rawText);
    res.json({ success: true, provider, result });
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : "AI analysis failed";
    res.status(500).json({ error: msg });
  }
});

// ─── Route: Cross-Verify — algo engine vs. Gemini AI (Replit managed key) ────

router.post("/cross-verify", async (req, res) => {
  try {
    const {
      symbol,
      symboltoken,
      exchange = "NSE",
      interval = "FIFTEEN_MINUTE",
    } = req.body as {
      symbol: string;
      symboltoken?: string;
      exchange?: string;
      interval?: string;
    };

    if (!symbol) {
      res.status(400).json({ error: "symbol is required" });
      return;
    }

    // Resolve token
    let token = symboltoken;
    if (!token) {
      const stock = NIFTY50.find(s => s.symbol === symbol || s.symbol === `${symbol}-EQ`);
      token = stock?.token;
    }
    if (!token) {
      res.status(400).json({ error: `Token not found for symbol: ${symbol}` });
      return;
    }

    // 1. Fetch live candles from Angel One (reuse same helper as signals.ts)
    const candles = await fetchCandles(token, interval, exchange);

    if (candles.length < 20) {
      res.status(400).json({ error: `Insufficient candle data (got ${candles.length}, need 20+)` });
      return;
    }

    // 2. Run 20-indicator algorithm engine
    const algoResult = generateSignal(symbol, candles);
    const indicators = calculateIndicators(candles);
    const patterns = detectPatterns(candles);

    // Pass full indicators object — prompt builder accesses fields via `as any`
    const indicatorsPlain = indicators as unknown as Record<string, unknown>;

    const recentPrices = candles.slice(-20).map(c => c.close);

    // 3. Build cross-verify prompt and call Gemini (Replit-managed, no user key needed)
    const prompt = buildCrossVerifyPrompt({
      symbol: algoResult.symbol,
      interval,
      price: algoResult.entry,
      algoSignal: algoResult.signal,
      algoScore: algoResult.score,
      algoConfidence: algoResult.confidence,
      algoReasons: algoResult.reasons,
      indicators: indicatorsPlain,
      candlestickPatterns: patterns.candlestick ?? [],
      chartPatterns: patterns.chart ?? [],
      recentPrices,
    });

    const geminiResponse = await ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents: [{ role: "user", parts: [{ text: prompt }] }],
      config: { temperature: 0.2, maxOutputTokens: 8192, responseMimeType: "application/json" },
    });

    const rawText = geminiResponse.text ?? "";
    const aiResult = parseAIResponse(rawText);

    res.json({
      success: true,
      symbol: algoResult.symbol,
      price: algoResult.entry,
      interval,
      algo: {
        signal: algoResult.signal,
        score: algoResult.score,
        confidence: algoResult.confidence,
        reasons: algoResult.reasons,
        entry: algoResult.entry,
        target1: algoResult.target1,
        target2: algoResult.target2,
        target3: algoResult.target3,
        stopLoss: algoResult.stopLoss,
        riskReward: algoResult.riskReward,
      },
      ai: aiResult,
      patterns: {
        candlestick: patterns.candlestick ?? [],
        chart: patterns.chart ?? [],
      },
      analyzedAt: new Date().toISOString(),
    });
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : "Cross-verify failed";
    console.error("[AI Cross-Verify] Error:", msg);
    res.status(500).json({ error: msg });
  }
});

export default router;
